// Demo/Sample data for BRMS Demo Mode

export const demoResidents = [
  {
    id: '1',
    first_name: 'Juan',
    middle_name: 'Santos',
    last_name: 'Dela Cruz',
    suffix: '',
    birth_date: '1985-03-15',
    gender: 'Male',
    civil_status: 'Married',
    occupation: 'Teacher',
    contact_number: '09171234567',
    email: 'juan.delacruz@email.com',
    address: '123 Rizal Street',
    household_head: true,
    voter_status: true,
    pwd_status: false,
    senior_citizen: false,
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: '2',
    first_name: 'Maria',
    middle_name: 'Reyes',
    last_name: 'Dela Cruz',
    suffix: '',
    birth_date: '1988-07-22',
    gender: 'Female',
    civil_status: 'Married',
    occupation: 'Nurse',
    contact_number: '09181234567',
    email: 'maria.delacruz@email.com',
    address: '123 Rizal Street',
    household_head: false,
    voter_status: true,
    pwd_status: false,
    senior_citizen: false,
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: '3',
    first_name: 'Pedro',
    middle_name: 'Garcia',
    last_name: 'Santos',
    suffix: 'Jr.',
    birth_date: '1955-11-08',
    gender: 'Male',
    civil_status: 'Widowed',
    occupation: 'Retired',
    contact_number: '09191234567',
    email: 'pedro.santos@email.com',
    address: '456 Mabini Avenue',
    household_head: true,
    voter_status: true,
    pwd_status: false,
    senior_citizen: true,
    created_at: '2024-02-20T10:30:00Z',
  },
  {
    id: '4',
    first_name: 'Ana',
    middle_name: 'Lopez',
    last_name: 'Reyes',
    suffix: '',
    birth_date: '1992-04-12',
    gender: 'Female',
    civil_status: 'Single',
    occupation: 'Software Developer',
    contact_number: '09201234567',
    email: 'ana.reyes@email.com',
    address: '789 Bonifacio Street',
    household_head: true,
    voter_status: true,
    pwd_status: false,
    senior_citizen: false,
    created_at: '2024-03-05T14:15:00Z',
  },
  {
    id: '5',
    first_name: 'Roberto',
    middle_name: 'Cruz',
    last_name: 'Fernandez',
    suffix: '',
    birth_date: '1978-09-30',
    gender: 'Male',
    civil_status: 'Married',
    occupation: 'Business Owner',
    contact_number: '09211234567',
    email: 'roberto.fernandez@email.com',
    address: '321 Luna Street',
    household_head: true,
    voter_status: true,
    pwd_status: false,
    senior_citizen: false,
    created_at: '2024-03-10T09:45:00Z',
  },
  {
    id: '6',
    first_name: 'Elena',
    middle_name: 'Martinez',
    last_name: 'Gonzales',
    suffix: '',
    birth_date: '1960-01-25',
    gender: 'Female',
    civil_status: 'Married',
    occupation: 'Housewife',
    contact_number: '09221234567',
    email: 'elena.gonzales@email.com',
    address: '654 Aguinaldo Road',
    household_head: false,
    voter_status: true,
    pwd_status: true,
    senior_citizen: true,
    created_at: '2024-04-01T11:20:00Z',
  },
  {
    id: '7',
    first_name: 'Carlos',
    middle_name: 'Villanueva',
    last_name: 'Ramos',
    suffix: '',
    birth_date: '1995-06-18',
    gender: 'Male',
    civil_status: 'Single',
    occupation: 'Call Center Agent',
    contact_number: '09231234567',
    email: 'carlos.ramos@email.com',
    address: '987 Quezon Boulevard',
    household_head: false,
    voter_status: true,
    pwd_status: false,
    senior_citizen: false,
    created_at: '2024-04-15T13:00:00Z',
  },
  {
    id: '8',
    first_name: 'Lourdes',
    middle_name: 'Aquino',
    last_name: 'Bautista',
    suffix: '',
    birth_date: '1970-12-05',
    gender: 'Female',
    civil_status: 'Married',
    occupation: 'Market Vendor',
    contact_number: '09241234567',
    email: 'lourdes.bautista@email.com',
    address: '147 Magsaysay Street',
    household_head: true,
    voter_status: true,
    pwd_status: false,
    senior_citizen: false,
    created_at: '2024-05-01T07:30:00Z',
  },
];

export const demoClearances = [
  {
    id: '1',
    resident_id: '1',
    resident_name: 'Juan Santos Dela Cruz',
    clearance_type: 'Barangay Clearance',
    purpose: 'Employment',
    status: 'approved',
    amount: 50,
    or_number: 'OR-2024-001',
    issued_date: '2024-11-25',
    valid_until: '2025-05-25',
    created_at: '2024-11-25T08:00:00Z',
  },
  {
    id: '2',
    resident_id: '2',
    resident_name: 'Maria Reyes Dela Cruz',
    clearance_type: 'Certificate of Residency',
    purpose: 'School Enrollment',
    status: 'approved',
    amount: 30,
    or_number: 'OR-2024-002',
    issued_date: '2024-11-26',
    valid_until: '2025-05-26',
    created_at: '2024-11-26T09:30:00Z',
  },
  {
    id: '3',
    resident_id: '4',
    resident_name: 'Ana Lopez Reyes',
    clearance_type: 'Business Permit Clearance',
    purpose: 'Business Registration',
    status: 'pending',
    amount: 100,
    or_number: null,
    issued_date: null,
    valid_until: null,
    created_at: '2024-11-28T14:00:00Z',
  },
  {
    id: '4',
    resident_id: '5',
    resident_name: 'Roberto Cruz Fernandez',
    clearance_type: 'Barangay Clearance',
    purpose: 'Loan Application',
    status: 'approved',
    amount: 50,
    or_number: 'OR-2024-003',
    issued_date: '2024-11-27',
    valid_until: '2025-05-27',
    created_at: '2024-11-27T10:15:00Z',
  },
  {
    id: '5',
    resident_id: '3',
    resident_name: 'Pedro Garcia Santos Jr.',
    clearance_type: 'Certificate of Indigency',
    purpose: 'Medical Assistance',
    status: 'approved',
    amount: 0,
    or_number: 'OR-2024-004',
    issued_date: '2024-11-28',
    valid_until: '2025-02-28',
    created_at: '2024-11-28T11:45:00Z',
  },
];

export const demoBlotters = [
  {
    id: '1',
    case_number: 'BLT-2024-001',
    incident_type: 'Noise Complaint',
    incident_date: '2024-11-20',
    incident_time: '22:30',
    incident_location: '123 Rizal Street',
    complainant_name: 'Juan Dela Cruz',
    complainant_address: '125 Rizal Street',
    complainant_contact: '09171234567',
    respondent_name: 'Unknown',
    respondent_address: '123 Rizal Street',
    narrative: 'Complainant reported loud music coming from the neighboring house past 10 PM.',
    status: 'resolved',
    action_taken: 'Verbal warning issued to the respondent. Both parties agreed to maintain peace.',
    created_at: '2024-11-20T23:00:00Z',
  },
  {
    id: '2',
    case_number: 'BLT-2024-002',
    incident_type: 'Physical Altercation',
    incident_date: '2024-11-22',
    incident_time: '15:45',
    incident_location: 'Public Market',
    complainant_name: 'Maria Santos',
    complainant_address: '456 Mabini Avenue',
    complainant_contact: '09181234567',
    respondent_name: 'Pedro Reyes',
    respondent_address: '789 Bonifacio Street',
    narrative: 'Verbal argument between two vendors escalated to pushing. No serious injuries reported.',
    status: 'under_investigation',
    action_taken: 'Statements taken from both parties. Scheduled for mediation.',
    created_at: '2024-11-22T16:00:00Z',
  },
  {
    id: '3',
    case_number: 'BLT-2024-003',
    incident_type: 'Property Dispute',
    incident_date: '2024-11-25',
    incident_time: '09:00',
    incident_location: '321 Luna Street',
    complainant_name: 'Roberto Fernandez',
    complainant_address: '321 Luna Street',
    complainant_contact: '09211234567',
    respondent_name: 'Carlos Mendoza',
    respondent_address: '323 Luna Street',
    narrative: 'Dispute over property boundary. Complainant claims respondent built fence on his property.',
    status: 'pending',
    action_taken: 'Initial hearing scheduled for next week.',
    created_at: '2024-11-25T09:30:00Z',
  },
];

export const demoFinancials = [
  {
    id: '1',
    transaction_type: 'income',
    category: 'Clearance Fees',
    description: 'Barangay Clearance - Juan Dela Cruz',
    amount: 50,
    reference_number: 'OR-2024-001',
    transaction_date: '2024-11-25',
    created_at: '2024-11-25T08:00:00Z',
  },
  {
    id: '2',
    transaction_type: 'income',
    category: 'Clearance Fees',
    description: 'Certificate of Residency - Maria Dela Cruz',
    amount: 30,
    reference_number: 'OR-2024-002',
    transaction_date: '2024-11-26',
    created_at: '2024-11-26T09:30:00Z',
  },
  {
    id: '3',
    transaction_type: 'expense',
    category: 'Office Supplies',
    description: 'Purchase of bond paper and ink',
    amount: 1500,
    reference_number: 'EXP-2024-001',
    transaction_date: '2024-11-24',
    created_at: '2024-11-24T10:00:00Z',
  },
  {
    id: '4',
    transaction_type: 'income',
    category: 'Clearance Fees',
    description: 'Barangay Clearance - Roberto Fernandez',
    amount: 50,
    reference_number: 'OR-2024-003',
    transaction_date: '2024-11-27',
    created_at: '2024-11-27T10:15:00Z',
  },
  {
    id: '5',
    transaction_type: 'expense',
    category: 'Utilities',
    description: 'Electric bill for November 2024',
    amount: 3500,
    reference_number: 'EXP-2024-002',
    transaction_date: '2024-11-28',
    created_at: '2024-11-28T14:00:00Z',
  },
  {
    id: '6',
    transaction_type: 'income',
    category: 'Business Permits',
    description: 'Business Permit Renewal - Sari-sari Store',
    amount: 500,
    reference_number: 'OR-2024-005',
    transaction_date: '2024-11-28',
    created_at: '2024-11-28T15:30:00Z',
  },
  {
    id: '7',
    transaction_type: 'expense',
    category: 'Maintenance',
    description: 'Barangay Hall cleaning services',
    amount: 2000,
    reference_number: 'EXP-2024-003',
    transaction_date: '2024-11-29',
    created_at: '2024-11-29T08:00:00Z',
  },
];

export const demoDocuments = [
  {
    id: '1',
    name: 'Barangay Ordinance 2024-001.pdf',
    type: 'application/pdf',
    size: 245000,
    folder_id: null,
    created_at: '2024-10-15T08:00:00Z',
  },
  {
    id: '2',
    name: 'Annual Budget Report 2024.xlsx',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 128000,
    folder_id: null,
    created_at: '2024-11-01T10:30:00Z',
  },
  {
    id: '3',
    name: 'Barangay Assembly Minutes - Nov 2024.docx',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 85000,
    folder_id: null,
    created_at: '2024-11-20T14:00:00Z',
  },
  {
    id: '4',
    name: 'Development Plan 2024-2027.pdf',
    type: 'application/pdf',
    size: 1250000,
    folder_id: null,
    created_at: '2024-09-01T09:00:00Z',
  },
];

export const demoFolders = [
  {
    id: '1',
    name: 'Ordinances',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Financial Reports',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Meeting Minutes',
    created_at: '2024-01-01T00:00:00Z',
  },
];

export const demoDashboardStats = {
  totalResidents: 1247,
  totalHouseholds: 312,
  pendingClearances: 8,
  monthlyIncome: 15680,
  totalClearances: 156,
  totalBlotters: 23,
  resolvedBlotters: 18,
  seniorCitizens: 89,
  pwdResidents: 34,
  registeredVoters: 892,
};

export const demoBarangayInfo = {
  id: 'demo-barangay',
  name: 'Barangay San Miguel',
  municipality: 'Sample City',
  province: 'Sample Province',
  region: 'Region IV-A',
  address: '123 Main Street, San Miguel',
  contact_number: '(02) 8123-4567',
  email: 'sanmiguel@sample.gov.ph',
  captain_name: 'Hon. Demo User',
  logo_url: null,
};
