// TypeScript Database Types
// Auto-generated type definitions for Supabase tables
// You can regenerate these using: npx supabase gen types typescript --project-id your-project-ref

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          auth0_id: string;
          email: string;
          name: string | null;
          picture: string | null;
          role: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth0_id: string;
          email: string;
          name?: string | null;
          picture?: string | null;
          role?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth0_id?: string;
          email?: string;
          name?: string | null;
          picture?: string | null;
          role?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      residents: {
        Row: {
          id: string;
          first_name: string;
          middle_name: string | null;
          last_name: string;
          suffix: string | null;
          nickname: string | null;
          date_of_birth: string;
          place_of_birth: string | null;
          gender: string;
          civil_status: string;
          email: string | null;
          phone: string | null;
          mobile: string | null;
          house_number: string | null;
          street: string | null;
          purok: string | null;
          barangay: string;
          city_municipality: string;
          province: string;
          zip_code: string | null;
          residency_status: string;
          years_of_residency: number | null;
          voter_status: string | null;
          voter_id: string | null;
          occupation: string | null;
          employer: string | null;
          monthly_income: number | null;
          emergency_contact_name: string | null;
          emergency_contact_relationship: string | null;
          emergency_contact_phone: string | null;
          religion: string | null;
          nationality: string | null;
          educational_attainment: string | null;
          photo_url: string | null;
          is_active: boolean;
          is_archived: boolean;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          middle_name?: string | null;
          last_name: string;
          suffix?: string | null;
          nickname?: string | null;
          date_of_birth: string;
          place_of_birth?: string | null;
          gender: string;
          civil_status: string;
          email?: string | null;
          phone?: string | null;
          mobile?: string | null;
          house_number?: string | null;
          street?: string | null;
          purok?: string | null;
          barangay: string;
          city_municipality: string;
          province: string;
          zip_code?: string | null;
          residency_status: string;
          years_of_residency?: number | null;
          voter_status?: string | null;
          voter_id?: string | null;
          occupation?: string | null;
          employer?: string | null;
          monthly_income?: number | null;
          emergency_contact_name?: string | null;
          emergency_contact_relationship?: string | null;
          emergency_contact_phone?: string | null;
          religion?: string | null;
          nationality?: string | null;
          educational_attainment?: string | null;
          photo_url?: string | null;
          is_active?: boolean;
          is_archived?: boolean;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          middle_name?: string | null;
          last_name?: string;
          suffix?: string | null;
          nickname?: string | null;
          date_of_birth?: string;
          place_of_birth?: string | null;
          gender?: string;
          civil_status?: string;
          email?: string | null;
          phone?: string | null;
          mobile?: string | null;
          house_number?: string | null;
          street?: string | null;
          purok?: string | null;
          barangay?: string;
          city_municipality?: string;
          province?: string;
          zip_code?: string | null;
          residency_status?: string;
          years_of_residency?: number | null;
          voter_status?: string | null;
          voter_id?: string | null;
          occupation?: string | null;
          employer?: string | null;
          monthly_income?: number | null;
          emergency_contact_name?: string | null;
          emergency_contact_relationship?: string | null;
          emergency_contact_phone?: string | null;
          religion?: string | null;
          nationality?: string | null;
          educational_attainment?: string | null;
          photo_url?: string | null;
          is_active?: boolean;
          is_archived?: boolean;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          document_type: string;
          document_number: string;
          resident_id: string | null;
          resident_name: string;
          purpose: string;
          validity_period: number | null;
          issue_date: string;
          expiry_date: string | null;
          status: string;
          requested_date: string;
          approved_date: string | null;
          approved_by: string | null;
          issued_by: string | null;
          fee_amount: number;
          or_number: string | null;
          payment_date: string | null;
          payment_status: string;
          remarks: string | null;
          attachments: Json | null;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          document_type: string;
          document_number: string;
          resident_id?: string | null;
          resident_name: string;
          purpose: string;
          validity_period?: number | null;
          issue_date?: string;
          expiry_date?: string | null;
          status?: string;
          requested_date?: string;
          approved_date?: string | null;
          approved_by?: string | null;
          issued_by?: string | null;
          fee_amount?: number;
          or_number?: string | null;
          payment_date?: string | null;
          payment_status?: string;
          remarks?: string | null;
          attachments?: Json | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          document_type?: string;
          document_number?: string;
          resident_id?: string | null;
          resident_name?: string;
          purpose?: string;
          validity_period?: number | null;
          issue_date?: string;
          expiry_date?: string | null;
          status?: string;
          requested_date?: string;
          approved_date?: string | null;
          approved_by?: string | null;
          issued_by?: string | null;
          fee_amount?: number;
          or_number?: string | null;
          payment_date?: string | null;
          payment_status?: string;
          remarks?: string | null;
          attachments?: Json | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      blotter_records: {
        Row: {
          id: string;
          blotter_number: string;
          incident_date: string;
          reported_date: string;
          incident_type: string;
          incident_category: string | null;
          incident_location: string;
          incident_description: string;
          complainant_id: string | null;
          complainant_name: string;
          complainant_contact: string | null;
          complainant_address: string | null;
          respondent_id: string | null;
          respondent_name: string;
          respondent_contact: string | null;
          respondent_address: string | null;
          witnesses: Json | null;
          status: string;
          priority: string;
          resolution_date: string | null;
          resolution_details: string | null;
          settlement_agreement: string | null;
          actions_taken: string | null;
          referred_to: string | null;
          referral_date: string | null;
          recorded_by: string | null;
          assigned_to: string | null;
          resolved_by: string | null;
          attachments: Json | null;
          is_archived: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          blotter_number: string;
          incident_date: string;
          reported_date?: string;
          incident_type: string;
          incident_category?: string | null;
          incident_location: string;
          incident_description: string;
          complainant_id?: string | null;
          complainant_name: string;
          complainant_contact?: string | null;
          complainant_address?: string | null;
          respondent_id?: string | null;
          respondent_name: string;
          respondent_contact?: string | null;
          respondent_address?: string | null;
          witnesses?: Json | null;
          status?: string;
          priority?: string;
          resolution_date?: string | null;
          resolution_details?: string | null;
          settlement_agreement?: string | null;
          actions_taken?: string | null;
          referred_to?: string | null;
          referral_date?: string | null;
          recorded_by?: string | null;
          assigned_to?: string | null;
          resolved_by?: string | null;
          attachments?: Json | null;
          is_archived?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          blotter_number?: string;
          incident_date?: string;
          reported_date?: string;
          incident_type?: string;
          incident_category?: string | null;
          incident_location?: string;
          incident_description?: string;
          complainant_id?: string | null;
          complainant_name?: string;
          complainant_contact?: string | null;
          complainant_address?: string | null;
          respondent_id?: string | null;
          respondent_name?: string;
          respondent_contact?: string | null;
          respondent_address?: string | null;
          witnesses?: Json | null;
          status?: string;
          priority?: string;
          resolution_date?: string | null;
          resolution_details?: string | null;
          settlement_agreement?: string | null;
          actions_taken?: string | null;
          referred_to?: string | null;
          referral_date?: string | null;
          recorded_by?: string | null;
          assigned_to?: string | null;
          resolved_by?: string | null;
          attachments?: Json | null;
          is_archived?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      financial_transactions: {
        Row: {
          id: string;
          transaction_number: string;
          transaction_date: string;
          transaction_type: string;
          category: string;
          amount: number;
          payment_method: string | null;
          or_number: string | null;
          reference_number: string | null;
          document_id: string | null;
          resident_id: string | null;
          payer_name: string | null;
          payee_name: string | null;
          description: string;
          remarks: string | null;
          status: string;
          processed_by: string | null;
          verified_by: string | null;
          fiscal_year: number | null;
          quarter: number | null;
          attachments: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          transaction_number: string;
          transaction_date?: string;
          transaction_type: string;
          category: string;
          amount: number;
          payment_method?: string | null;
          or_number?: string | null;
          reference_number?: string | null;
          document_id?: string | null;
          resident_id?: string | null;
          payer_name?: string | null;
          payee_name?: string | null;
          description: string;
          remarks?: string | null;
          status?: string;
          processed_by?: string | null;
          verified_by?: string | null;
          fiscal_year?: number | null;
          quarter?: number | null;
          attachments?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          transaction_number?: string;
          transaction_date?: string;
          transaction_type?: string;
          category?: string;
          amount?: number;
          payment_method?: string | null;
          or_number?: string | null;
          reference_number?: string | null;
          document_id?: string | null;
          resident_id?: string | null;
          payer_name?: string | null;
          payee_name?: string | null;
          description?: string;
          remarks?: string | null;
          status?: string;
          processed_by?: string | null;
          verified_by?: string | null;
          fiscal_year?: number | null;
          quarter?: number | null;
          attachments?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      settings: {
        Row: {
          id: string;
          barangay_name: string | null;
          barangay_logo_url: string | null;
          municipality: string | null;
          province: string | null;
          region: string | null;
          barangay_contact: string | null;
          barangay_email: string | null;
          barangay_website: string | null;
          barangay_captain: string | null;
          secretary: string | null;
          treasurer: string | null;
          document_validity_days: Json | null;
          document_fees: Json | null;
          fiscal_year_start: number | null;
          timezone: string | null;
          features: Json | null;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          barangay_name?: string | null;
          barangay_logo_url?: string | null;
          municipality?: string | null;
          province?: string | null;
          region?: string | null;
          barangay_contact?: string | null;
          barangay_email?: string | null;
          barangay_website?: string | null;
          barangay_captain?: string | null;
          secretary?: string | null;
          treasurer?: string | null;
          document_validity_days?: Json | null;
          document_fees?: Json | null;
          fiscal_year_start?: number | null;
          timezone?: string | null;
          features?: Json | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          barangay_name?: string | null;
          barangay_logo_url?: string | null;
          municipality?: string | null;
          province?: string | null;
          region?: string | null;
          barangay_contact?: string | null;
          barangay_email?: string | null;
          barangay_website?: string | null;
          barangay_captain?: string | null;
          secretary?: string | null;
          treasurer?: string | null;
          document_validity_days?: Json | null;
          document_fees?: Json | null;
          fiscal_year_start?: number | null;
          timezone?: string | null;
          features?: Json | null;
          updated_by?: string | null;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          changes: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          changes?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          changes?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      files: {
        Row: {
          id: string;
          bucket: string;
          storage_path: string;
          filename: string;
          original_filename: string;
          content_type: string;
          file_size: number;
          file_category: string;
          uploaded_by: string | null;
          owner_id: string | null;
          entity_type: string | null;
          entity_id: string | null;
          is_public: boolean;
          access_url: string | null;
          metadata: Json | null;
          description: string | null;
          tags: string[] | null;
          scan_status: string;
          scanned_at: string | null;
          is_archived: boolean;
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bucket?: string;
          storage_path: string;
          filename: string;
          original_filename: string;
          content_type: string;
          file_size: number;
          file_category: string;
          uploaded_by?: string | null;
          owner_id?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          is_public?: boolean;
          access_url?: string | null;
          metadata?: Json | null;
          description?: string | null;
          tags?: string[] | null;
          scan_status?: string;
          scanned_at?: string | null;
          is_archived?: boolean;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bucket?: string;
          storage_path?: string;
          filename?: string;
          original_filename?: string;
          content_type?: string;
          file_size?: number;
          file_category?: string;
          uploaded_by?: string | null;
          owner_id?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          is_public?: boolean;
          access_url?: string | null;
          metadata?: Json | null;
          description?: string | null;
          tags?: string[] | null;
          scan_status?: string;
          scanned_at?: string | null;
          is_archived?: boolean;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      barangay_folders: {
        Row: {
          id: string;
          barangay_id: string;
          folder_name: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          barangay_id: string;
          folder_name: string;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          barangay_id?: string;
          folder_name?: string;
          created_by?: string;
          created_at?: string;
        };
      };
      barangay_documents: {
        Row: {
          id: string;
          barangay_id: string;
          folder_id: string;
          file_name: string;
          file_url: string;
          file_type: string | null;
          file_size: number | null;
          storage_path: string;
          uploaded_by: string;
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          barangay_id: string;
          folder_id: string;
          file_name: string;
          file_url: string;
          file_type?: string | null;
          file_size?: number | null;
          storage_path: string;
          uploaded_by: string;
          uploaded_at?: string;
        };
        Update: {
          id?: string;
          barangay_id?: string;
          folder_id?: string;
          file_name?: string;
          file_url?: string;
          file_type?: string | null;
          file_size?: number | null;
          storage_path?: string;
          uploaded_by?: string;
          uploaded_at?: string;
        };
      };
      barangay_activity_logs: {
        Row: {
          id: string;
          barangay_id: string;
          action: string;
          user_id: string;
          document_id: string | null;
          folder_id: string | null;
          timestamp: string;
          details: Json | null;
        };
        Insert: {
          id?: string;
          barangay_id: string;
          action: string;
          user_id: string;
          document_id?: string | null;
          folder_id?: string | null;
          timestamp?: string;
          details?: Json | null;
        };
        Update: {
          id?: string;
          barangay_id?: string;
          action?: string;
          user_id?: string;
          document_id?: string | null;
          folder_id?: string | null;
          timestamp?: string;
          details?: Json | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
